language: python

dist: bionic          # required for Python >= 3.7
python: 3.7           
sudo: required
addons:
  apt:
    update: true

install: 
  - pip install --upgrade pip  
  - pip install -r requirements.txt
  - pip install ./python/.

script: 
  - pytest ./python/test/
  - rrsg_cgreco 